In [269]:
import pandas as pd

df = pd.read_csv("../data/raw/IPL.csv")

print(df.shape)
df.head()

C:\Users\Shiva\AppData\Local\Temp\ipykernel_2712\2085303613.py:3: DtypeWarning: Columns (0: review_batter, 1: team_reviewed, 2: review_decision, 3: umpire, 4: season, 5: superover_winner, 6: result_type, 7: method, 8: event_match_no) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/IPL.csv")

(278205, 64)

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,131972,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [270]:
df = df[[
    'match_id',
    'date',
    'batting_team',
    'bowling_team',
    'venue',
    'batter',
    'bowler',
    'runs_total',
    'wicket_kind'
]]

In [271]:
df.head()

,match_id,date,batting_team,bowling_team,venue,batter,bowler,runs_total,wicket_kind
0,335982,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,SC Ganguly,P Kumar,1,NaN
1,335982,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,BB McCullum,P Kumar,0,NaN
2,335982,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,BB McCullum,P Kumar,1,NaN
3,335982,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,BB McCullum,P Kumar,0,NaN
4,335982,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,BB McCullum,P Kumar,0,NaN

In [272]:
df.isnull().sum()

match_id             0
date                 0
batting_team         0
bowling_team         0
venue                0
batter               0
bowler               0
runs_total           0
wicket_kind     264382
dtype: int64

In [273]:
df['wicket_kind'] = df['wicket_kind'].fillna('None')

In [274]:
df['date'] = pd.to_datetime(df['date'])

In [275]:
df['batting_team'] = df['batting_team'].replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings'
})

df['bowling_team'] = df['bowling_team'].replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings'
})

In [276]:
team_scores = df.groupby(['match_id', 'batting_team'])['runs_total'].sum().reset_index()

In [277]:
team_scores.head()

   match_id                 batting_team  runs_total
0    335982        Kolkata Knight Riders         222
1    335982  Royal Challengers Bangalore          82
2    335983          Chennai Super Kings         240
3    335983                 Punjab Kings         207
4    335984               Delhi Capitals         132

In [278]:
team_scores.to_csv("../data/processed/team_scores.csv", index=False)

In [279]:
match_df = team_scores.pivot(index='match_id', columns='batting_team', values='runs_total').reset_index()

In [280]:
match_df.head()

batting_team,match_id,Chennai Super Kings,Deccan Chargers,Delhi Capitals,Gujarat Lions,Gujarat Titans,Kochi Tuskers Kerala,Kolkata Knight Riders,Lucknow Super Giants,Mumbai Indians,Pune Warriors,Punjab Kings,Rajasthan Royals,Rising Pune Supergiant,Rising Pune Supergiants,Royal Challengers Bangalore,Royal Challengers Bengaluru,Sunrisers Hyderabad
0,335982,NaN,NaN,NaN,NaN,NaN,NaN,222.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.0,NaN,NaN
1,335983,240.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,207.0,NaN,NaN,NaN,NaN,NaN,NaN
2,335984,NaN,NaN,132.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129.0,NaN,NaN,NaN,NaN,NaN
3,335985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165.0,NaN,NaN,NaN,NaN,NaN,166.0,NaN,NaN
4,335986,NaN,110.0,NaN,NaN,NaN,NaN,112.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [281]:
def process_match(x):
    # Only keep matches with exactly 2 teams
    if len(x) != 2:
        return None
    
    team1 = x.iloc[0]['batting_team']
    team2 = x.iloc[1]['batting_team']
    
    score1 = x.iloc[0]['runs_total']
    score2 = x.iloc[1]['runs_total']
    
    winner = team1 if score1 > score2 else team2
    
    return pd.Series({
        'team1': team1,
        'team2': team2,
        'score1': score1,
        'score2': score2,
        'winner': winner
    })

match_df = team_scores.groupby('match_id').apply(process_match).dropna().reset_index()

In [282]:
match_df.head()

,match_id,team1,team2,score1,score2,winner
0,335982,Kolkata Knight Riders,Royal Challengers Bangalore,222.0,82.0,Kolkata Knight Riders
1,335983,Chennai Super Kings,Punjab Kings,240.0,207.0,Chennai Super Kings
2,335984,Delhi Capitals,Rajasthan Royals,132.0,129.0,Delhi Capitals
3,335985,Mumbai Indians,Royal Challengers Bangalore,165.0,166.0,Royal Challengers Bangalore
4,335986,Deccan Chargers,Kolkata Knight Riders,110.0,112.0,Kolkata Knight Riders

In [283]:
match_df.to_csv("../data/processed/match_results.csv", index=False)

In [284]:
#Creating players Runs per match

In [285]:
player_runs = df.groupby(['match_id', 'batter'])['runs_total'].sum().reset_index()

In [286]:
player_runs.head()

   match_id       batter  runs_total
0    335982    AA Noffke          11
1    335982      B Akhil           0
2    335982  BB McCullum         169
3    335982     CL White           6
4    335982    DJ Hussey          12

In [287]:
player_runs = player_runs.sort_values(by=['batter', 'match_id'])

In [288]:
player_runs['form'] = player_runs.groupby('batter')['runs_total'].rolling(5).mean().reset_index(0, drop=True)

In [289]:

player_runs.head(10)

      match_id          batter  runs_total  form
4299    548346  A Ashish Reddy          10   NaN
4390    548352  A Ashish Reddy           3   NaN
4496    548359  A Ashish Reddy          12   NaN
4699    548373  A Ashish Reddy          10   NaN
4747    548376  A Ashish Reddy           5   8.0
4866    598000  A Ashish Reddy           7   7.4
4933    598004  A Ashish Reddy          14   9.6
5027    598010  A Ashish Reddy          16  10.4
5076    598013  A Ashish Reddy           4   9.2
5160    598018  A Ashish Reddy          19  12.0

In [290]:
player_runs['form'] = player_runs['form'].fillna(0)

In [291]:
player_runs.to_csv("../data/processed/player_form.csv", index=False)

#SECTION 5 Feature Engineering

In [292]:
df = df.merge(player_runs[['match_id', 'batter', 'form']], 
              on=['match_id', 'batter'], 
              how='left')

In [293]:
team_form = df.groupby(['match_id', 'batting_team'])['form'].mean().reset_index()

In [294]:
final_df = match_df.merge(team_form, 
                          left_on=['match_id', 'team1'], 
                          right_on=['match_id', 'batting_team'], 
                          how='left')

final_df = final_df.rename(columns={'form': 'team1_form'}).drop('batting_team', axis=1)

final_df = final_df.merge(team_form, 
                          left_on=['match_id', 'team2'], 
                          right_on=['match_id', 'batting_team'], 
                          how='left')

final_df = final_df.rename(columns={'form': 'team2_form'}).drop('batting_team', axis=1)

In [295]:
final_df.head(40)

,match_id,team1,team2,score1,score2,winner,team1_form,team2_form
0,335982,Kolkata Knight Riders,Royal Challengers Bangalore,222.0,82.0,Kolkata Knight Riders,0.000000,0.000000
1,335983,Chennai Super Kings,Punjab Kings,240.0,207.0,Chennai Super Kings,0.000000,0.000000
2,335984,Delhi Capitals,Rajasthan Royals,132.0,129.0,Delhi Capitals,0.000000,0.000000
3,335985,Mumbai Indians,Royal Challengers Bangalore,165.0,166.0,Royal Challengers Bangalore,0.000000,0.000000
4,335986,Deccan Chargers,Kolkata Knight Riders,110.0,112.0,Kolkata Knight Riders,0.000000,0.000000
5,335987,Punjab Kings,Rajasthan Royals,166.0,168.0,Rajasthan Royals,0.000000,0.000000
6,335988,Deccan Chargers,Delhi Capitals,142.0,143.0,Delhi Capitals,0.000000,0.000000
7,335989,Chennai Super Kings,Mumbai Indians,208.0,202.0,Chennai Super Kings,0.000000,0.000000
8,335990,Deccan Chargers,Rajasthan Royals,214.0,217.0,Rajasthan Royals,0.000000,0.000000
9,335991,Mumbai Indians,Punjab Kings,116.0,182.0,Punjab Kings,0.000000,0.000000
10,335992,Rajasthan Royals,Royal Challengers Bangalore,138.0,135.0,Rajasthan Royals,0.000000,0.000000
11,335993,Chennai Super Kings,Kolkata Knight Riders,152.0,147.0,Chennai Super Kings,0.000000,0.000000
12,335994,Deccan Chargers,Mumbai Indians,155.0,154.0,Deccan Chargers,0.000000,0.000000
13,335995,Delhi Capitals,Punjab Kings,158.0,162.0,Punjab Kings,0.000000,0.000000
14,335996,Chennai Super Kings,Royal Challengers Bangalore,178.0,165.0,Chennai Super Kings,0.000000,0.000000
15,335997,Kolkata Knight Riders,Mumbai Indians,137.0,138.0,Mumbai Indians,0.000000,12.862712
16,335998,Delhi Capitals,Royal Challengers Bangalore,191.0,181.0,Delhi Capitals,0.000000,15.019835
17,335999,Deccan Chargers,Punjab Kings,164.0,167.0,Punjab Kings,7.754098,3.900855
18,336000,Kolkata Knight Riders,Rajasthan Royals,151.0,196.0,Rajasthan Royals,13.837705,10.829921
19,336001,Chennai Super Kings,Delhi Capitals,169.0,172.0,Delhi Capitals,11.288889,34.830508
20,336002,Deccan Chargers,Royal Challengers Bangalore,165.0,171.0,Royal Challengers Bangalore,16.950794,10.566667
21,336003,Kolkata Knight Riders,Punjab Kings,169.0,178.0,Punjab Kings,17.922951,12.736000
22,336004,Delhi Capitals,Mumbai Indians,133.0,162.0,Mumbai Indians,12.031579,13.193548
23,336005,Chennai Super Kings,Rajasthan Royals,109.0,110.0,Rajasthan Royals,9.293103,4.791398
24,336006,Punjab Kings,Royal Challengers Bangalore,127.0,126.0,Punjab Kings,7.234188,17.895868
25,336007,Chennai Super Kings,Deccan Chargers,144.0,148.0,Deccan Chargers,14.937097,22.596429
26,336008,Mumbai Indians,Rajasthan Royals,104.0,103.0,Mumbai Indians,14.747475,10.163107
27,336009,Chennai Super Kings,Delhi Capitals,188.0,187.0,Chennai Super Kings,8.990400,34.790476
28,336010,Kolkata Knight Riders,Royal Challengers Bangalore,129.0,124.0,Kolkata Knight Riders,13.187755,14.109091
29,336011,Deccan Chargers,Rajasthan Royals,140.0,141.0,Rajasthan Royals,27.163934,28.857426
30,336012,Mumbai Indians,Royal Challengers Bangalore,126.0,122.0,Mumbai Indians,15.472549,11.495652
31,336013,Chennai Super Kings,Punjab Kings,181.0,163.0,Chennai Super Kings,23.383206,6.909836
32,336014,Deccan Chargers,Kolkata Knight Riders,181.0,204.0,Kolkata Knight Riders,22.982812,27.646774
33,336015,Delhi Capitals,Rajasthan Royals,156.0,159.0,Rajasthan Royals,18.539837,21.386885
34,336016,Punjab Kings,Royal Challengers Bangalore,144.0,143.0,Punjab Kings,38.245361,19.464516
35,336017,Delhi Capitals,Kolkata Knight Riders,110.0,133.0,Kolkata Knight Riders,6.470909,15.096875
36,336018,Chennai Super Kings,Mumbai Indians,156.0,158.0,Mumbai Indians,26.881890,34.885106
37,336019,Punjab Kings,Rajasthan Royals,221.0,180.0,Punjab Kings,49.129032,9.611570
38,336020,Deccan Chargers,Delhi Capitals,182.0,194.0,Delhi Capitals,22.173770,30.404800
39,336021,Kolkata Knight Riders,Mumbai Indians,67.0,68.0,Mumbai Indians,13.836735,36.573684

In [296]:
# Venue feature
venue_df = df[['match_id', 'venue']].drop_duplicates()

final_df = final_df.merge(venue_df, on='match_id', how='left')

final_df = pd.get_dummies(final_df, columns=['venue'])

In [297]:
#new feature toss diff
# Toss feature
toss_df = df[['match_id', 'batting_team']].drop_duplicates()

final_df = final_df.merge(toss_df, on='match_id', how='left')

final_df['team1_batting'] = (final_df['team1'] == final_df['batting_team']).astype(int)

In [298]:
# New feature form diff
final_df['form_diff'] = final_df['team1_form'] - final_df['team2_form']

In [299]:
final_df['target'] = (final_df['winner'] == final_df['team1']).astype(int)

In [300]:
model_df = final_df.drop(columns=['match_id', 'team1', 'team2', 'winner', 'batting_team'])

In [301]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

final_df = final_df.sort_values(by='match_id')

model_df = final_df[[
    'team1_form',
    'team2_form',
    'form_diff',
    'team1_batting',
    'target'
]]

X = model_df.drop('target', axis=1)
y = model_df['target']

split = int(len(X) * 0.8)

X_train = X.iloc[:split]
X_test = X.iloc[split:]

y_train = y.iloc[:split]
y_test = y.iloc[split:]

model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.05
)
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [302]:
y_pred = model.predict(X_test)

In [303]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6566523605150214

#SHAP ANALYSIS

In [ ]:
import shap

explainer = shap.Explainer(model)
shap_values = explainer(X_test)
shap.summary_plot(shap_values, X_test)

import matplotlib.pyplot as plt

ImportError: matplotlib is not installed so plotting is not available! Run `pip install matplotlib` to fix this.